# Generated by Django 4.0.6 on 2022-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0002_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
