# Generated by Django 4.0.6 on 2022-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dia', models.DateTimeField()),
                ('publicado', models.DateTimeField(auto_now=True)),
                ('modalidad', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('lugar', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/eventos')),
            ],
        ),
    ]
