# Generated by Django 4.0.6 on 2022-09-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='organiza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='publicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
