# Generated by Django 4.0.6 on 2022-09-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fotos',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='img',
            new_name='image',
        ),
    ]
