# Generated by Django 4.0.6 on 2022-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos_app', '0002_rename_fotos_photo_rename_img_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/tapaRevista')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
