# Generated by Django 4.0.6 on 2022-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos_app', '0003_revistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/biblioteca'),
        ),
    ]
